export const ADD_CHORES = 'ADD_CHORES';
export const CHORES_LOADING = 'CHORES_LOADING';
export const CHORES_FAILED = 'BEHAVIORS_FAILED';
export const ADD_CHORE = 'ADD_CHORE';
export const DELETE_CHORE = 'DELETE_CHORE';
export const EDIT_CHORE = 'EDIT_CHORE';
export const COMPLETE_CHORE = 'COMPLETE_CHORE';

export const ADD_BEHAVIORS = 'ADD_BEHAVIORS';
export const BEHAVIORS_LOADING = 'BEHAVIORS_LOADING';
export const BEHAVIORS_FAILED = 'BEHAVIORS_FAILED';
export const ADD_BEHAVIOR = 'ADD_BEHAVIOR';
export const DELETE_BEHAVIOR = 'DELETE_BEHAVIOR';
export const EDIT_BEHAVIOR = 'EDIT_BEHAVIOR';
export const PENDING_BEHAVIOR = 'PENDING_BEHAVIOR';

export const ADD_BEHAVIORQ = 'ADD_BEHAVIORQ';
export const DELETE_BEHAVIORQ = 'DELETE_BEHAVIORQ';
export const APPROVE_BEHAVIORQ = 'APPROVE_BEHAVIORQ';

export const ADD_REWARDS = 'ADD_REWARDS';
export const REWARDS_LOADING = 'REWARDS_LOADING';
export const REWARDS_FAILED = 'REWARDS_FAILED';
export const ADD_REWARD = 'ADD_REWARD';
export const DELETE_REWARD = 'DELETE_REWARD';
export const EDIT_REWARD = 'EDIT_REWARD';

export const ADD_REWARDSQ = 'ADD_REWARDSQ';
export const DELETE_REWARDSQ = 'DELETE_REWARDSQ';
export const APPROVE_REWARDSQ = 'APPROVE_REWARDSQ';

export const ADD_POINTS = 'ADD_POINTS';

export const ADD_SETTING = 'ADD_SETTING';
export const DELETE_SETTING = 'DELETE_SETTING';
export const EDIT_SETTING = 'EDIT_SETTING';

export const RESET_SETTINGS = 'RESET_SETTINGS';
export const RESET_CHORES = 'RESET_CHORES';
export const RESET_BEHAVIORS = 'RESET_BEHAVIORS';
export const RESET_BEHAVIORQ = 'RESET_BEHAVIORQ';
export const RESET_REWARDS = 'RESET_REWARDS';
export const RESET_REWARDSQ = 'RESET_REWARDSQ';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_FAMILY = 'ADD_FAMILY';
export const FAMILY_LOADING = 'FAMILY_LOADING';
export const FAMILY_FAILED = 'BEHAVIORS_FAILED';
export const SET_ACTIVE_CHILD = 'SET_ACTIVE_CHILD';
